---
apiVersion: infrahub.app/v1
kind: Schema
spec:
  description: |
    This schema extension contains models for SNMP Communities and SNMP Clients.
    As you can see this extension is not linked to Tenancy or Device, as you could
    decide to link the Community to different models based on your use case.
