---
ci_config: &ci_config
  - ".github/workflows/ci.yml"
  - ".github/file-filters.yml"

github_workflows: &github_workflows
  - ".github/workflows/*.yml"

yaml_all: &yaml_all
  - "**/*.{yml,yaml}"

markdown_all: &markdown_all
  - "**/*.{md,mdx}"
