---
# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint

default: true

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 4

# MD013/line-length - Line length (disabled for readability in prose)
MD013: false

# MD024/no-duplicate-heading - Multiple headings with the same content
# Allow duplicate headings in different sections
MD024:
  siblings_only: true

# MD025/single-title - Multiple top-level headings
# Prevent collisions with h1s and frontmatter titles
MD025:
  front_matter_title: ""

# MD033/no-inline-html - Inline HTML (disabled for MDX React components)
MD033: false

# MD060/table-column-style - Table column style (disabled for generated tables)
MD060: false
