---
apiVersion: infrahub.app/v1
kind: Schema
spec:
  description: This schema extension is the most detailed when it comes to location, you'll find all the layers you can think of.
  dependencies:
    - base