import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  schemaSidebar: [
    'home',
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference', // Generate sidebar slice from docs/api
        },
      ],
    },
    'contributing',
  ]
};

export default sidebars;
